routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\DistritoController;
use App\Http\Controllers\AlumnoController;
use App\Http\Controllers\AreaController;
use App\Http\Controllers\EtniaController;
use App\Http\Controllers\Profesiones´´Controller;
use App\Http\Controllers\Cargos´´Controller;
use App\Http\Controllers\Sexo´´Controller;
use App\Http\Controllers\Curso´´Controller;
use App\Http\Controllers\Asignacion´´Controller;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/login', function () {
    return redirect('/admin/login');
});

Route::get('/register', function () {
    return redirect('/admin');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('distritos', DistritoController::class)->only(['index', 'create', 'store']);
Route::resource('alumnos', AlumnoController::class)->only(['index', 'create', 'store']);
Route::resource('areas', AreaController::class)->only(['index', 'create', 'store']);
Route::resource('etnias', EtniaController::class)->only(['index', 'create', 'store']);
Route::resource('profesiones', Profesiones´´Controller::class)->only(['index', 'create', 'store']);
Route::resource('cargos', Cargos´´Controller::class)->only(['index', 'create', 'store']);
Route::resource('sexs', Sexo´´Controller::class)->only(['index', 'create', 'store']);
Route::resource('cursos', Curso´´Controller::class)->only(['index', 'create', 'store']);
Route::resource('asignaciones', Asignacion´´Controller::class)->only(['index', 'create', 'store']);
Route::get('/export', [App\Http\Controllers\ProductController::class,'export'])->name('products.export');

Route::get('/admin/password/reset', function () {
    return redirect('/password/reset');
})->middleware('guest')->name('password.request');


Route::get('/password', function () {

    return redirect('/password/reset');
});

Route::get('/', function () {

    return redirect('/admin');
});

app/Models/Profesiones.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Profesiones extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',

    ];

    public function profesion()
    {
        return $this->belongsTo(Profesiones::class);
    }
}

resources/views/profesiones/import-excel.blade.php
@extends('crudbooster::admin_template')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Importar Profesion</div>

                <div class="card-body">
                    @if (isset($errors) && $errors->any())
                    <div class="alert alert-danger" role="alert">
                        @foreach ($errors->all() as $error)
                        {{$error}}
                        @endforeach
                    </div>
                    @endif

                    <form action="{{route('profesiones.store')}}" method="POST" enctype="multipart/form-data"required>
                        @csrf

                        <input type="file" name="import_file" required/>

                        <button class="btn btn-primary" type="submit" required>Importar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/profesiones/index.blade.php
@extends('crudbooster::admin_template')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><h1> <b> Profesiones </b> </h1>
                    <a href="{{route('profesiones.create')}}" class="btn btn-info float-right">Importar Profesiones</a>

                    <a href="{{url('admin/profesiones') }}" class="btn btn-primary float-right">Ver Registros</a>


                </div>

                <div class="card-body">
                    @if (session('success'))
                    <div class="alert alert-success" role="alert">
                        {{ session('success') }}
                    </div>
                    @endif
                    <table class="table table-bordered table-striped profesiones_table" style="width: 100%;">
                        <thead>
                            <tr>


                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
    $(document).ready(function() {
        $('.profesiones_table').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{route('profesiones.index')}}",
            responsive: true,
            columns: [{
                data: 'name',
                    name: 'profesiones.name'
                }


            ]
        })
    })
</script>
@endsection